name             'datashades'
maintainer       'Queensland Government'
maintainer_email 'qol.development@smartservice.qld.gov.au'
license          'Apache-2.0'
description      'Installs and Configures a Scalable CKAN stack on AWS. Based on work by Link Digital.'
version          '0.1.0'
issues_url       'https://github.com/qld-gov-au/opswx-ckan-cookbook/issues'
source_url       'https://github.com/qld-gov-au/opswx-ckan-cookbook'
