#!/bin/bash

hostname=$1
dns=""
count=0
while [[ ${#dns} -eq 0  ]] && [ ${count} -lt 12 ]
do
	sleep 10
	dns=$(nslookup ${hostname} | grep Name:)
	((count++))
done

if [ ${#dns} -eq 0  ]; then
	exit 1
fi
