#!/bin/sh

# Check the amount of free memory (including disk cache and buffers);
# if it's less than 500MB, and Apache is running, then reload Apache.
# Not an ideal solution to memory leaks, but it's a universal one.
free -m |head -3 |tail -1 |awk '{print $4}' |grep '^[5-9][0-9][0-9]' > /dev/null || (service httpd status > /dev/null && service httpd reload)
