---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  # Quick check so we don't waste minutes if there's a Flake8 error
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b  # v1.321.0
        with:
          ruby-version: '3.1.7'
      - name: Install requirements
        run: |
          sudo apt-get install -y ruby-dev
          sudo gem install cookstyle
      - name: Check syntax
        run: cookstyle
